# Serena Project Configuration Template
# Copy to .serena/project.yml and customize

name: your-project-name
path: /path/to/your/project

# Detected programming languages
# Common values: typescript, python, go, java, rust, cpp
programming_languages:
  - typescript

# File encoding (usually utf-8)
file_encoding: utf-8

# Optional: Custom settings
# max_file_size: 1000000  # Max file size to index (bytes)
# exclude_patterns:       # Patterns to exclude from indexing
#   - "**/node_modules/**"
#   - "**/dist/**"
#   - "**/.git/**"
