# These are supported funding model platforms

github: [domelic]
# patreon: your-patreon-username
# open_collective: your-opencollective-username
# ko_fi: your-kofi-username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# lfx_crowdfunding: project-name
# custom: ["https://www.buymeacoffee.com/domelic"]
