# API Documentation Workflow
# Generates and deploys API documentation to GitHub Pages
# Supports: TypeDoc (TypeScript), Redocly (OpenAPI), Sphinx (Python)
# https://github.com/domelic/github-repository-setup

name: API Documentation

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "lib/**"
      - "openapi.yaml"
      - "openapi.json"
      - "docs/**"
      - "typedoc.json"
      - ".github/workflows/api-docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "lib/**"
      - "openapi.yaml"
      - "openapi.json"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ─────────────────────────────────────────────
  # Detect Documentation Type
  # ─────────────────────────────────────────────
  detect:
    name: Detect Doc Type
    runs-on: ubuntu-latest
    outputs:
      doc_type: ${{ steps.detect.outputs.type }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect documentation type
        id: detect
        run: |
          if [ -f "typedoc.json" ] || [ -f "tsconfig.json" ]; then
            echo "type=typedoc" >> $GITHUB_OUTPUT
          elif [ -f "openapi.yaml" ] || [ -f "openapi.json" ]; then
            echo "type=openapi" >> $GITHUB_OUTPUT
          elif [ -f "docs/conf.py" ]; then
            echo "type=sphinx" >> $GITHUB_OUTPUT
          else
            echo "type=typedoc" >> $GITHUB_OUTPUT
          fi

  # ─────────────────────────────────────────────
  # Build TypeDoc Documentation
  # ─────────────────────────────────────────────
  build-typedoc:
    name: Build TypeDoc
    runs-on: ubuntu-latest
    needs: detect
    if: needs.detect.outputs.doc_type == 'typedoc'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate TypeDoc
        run: |
          npx typedoc --out docs-dist \
            --plugin typedoc-plugin-markdown \
            --readme README.md \
            --name "API Documentation" \
            --includeVersion

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-dist

  # ─────────────────────────────────────────────
  # Build OpenAPI Documentation
  # ─────────────────────────────────────────────
  build-openapi:
    name: Build OpenAPI (Redocly)
    runs-on: ubuntu-latest
    needs: detect
    if: needs.detect.outputs.doc_type == 'openapi'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Find OpenAPI spec
        id: find_spec
        run: |
          if [ -f "openapi.yaml" ]; then
            echo "spec=openapi.yaml" >> $GITHUB_OUTPUT
          elif [ -f "openapi.json" ]; then
            echo "spec=openapi.json" >> $GITHUB_OUTPUT
          elif [ -f "api/openapi.yaml" ]; then
            echo "spec=api/openapi.yaml" >> $GITHUB_OUTPUT
          fi

      - name: Validate OpenAPI spec
        run: |
          npx @redocly/cli lint ${{ steps.find_spec.outputs.spec }}

      - name: Generate Redocly docs
        run: |
          mkdir -p docs-dist
          npx @redocly/cli build-docs ${{ steps.find_spec.outputs.spec }} \
            --output docs-dist/index.html \
            --title "API Documentation"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-dist

  # ─────────────────────────────────────────────
  # Build Sphinx Documentation (Python)
  # ─────────────────────────────────────────────
  build-sphinx:
    name: Build Sphinx
    runs-on: ubuntu-latest
    needs: detect
    if: needs.detect.outputs.doc_type == 'sphinx'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt 2>/dev/null || \
          pip install sphinx sphinx-rtd-theme myst-parser

      - name: Build Sphinx docs
        run: |
          cd docs
          make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  # ─────────────────────────────────────────────
  # Deploy to GitHub Pages
  # ─────────────────────────────────────────────
  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    needs: [detect, build-typedoc, build-openapi, build-sphinx]
    if: |
      always() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      (needs.build-typedoc.result == 'success' ||
       needs.build-openapi.result == 'success' ||
       needs.build-sphinx.result == 'success')

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # ─────────────────────────────────────────────
  # PR Preview Comment
  # ─────────────────────────────────────────────
  pr-comment:
    name: PR Preview
    runs-on: ubuntu-latest
    needs: [detect, build-typedoc, build-openapi, build-sphinx]
    if: |
      always() &&
      github.event_name == 'pull_request' &&
      (needs.build-typedoc.result == 'success' ||
       needs.build-openapi.result == 'success' ||
       needs.build-sphinx.result == 'success')

    permissions:
      pull-requests: write

    steps:
      - name: Add PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## :books: API Documentation Preview

            Documentation was generated successfully from this PR.

            **Doc Type:** `${{ needs.detect.outputs.doc_type }}`

            Once merged, docs will be available at:
            `https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/`

            ---
            *Generated by [API Docs Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})*

# ─────────────────────────────────────────────────────
# SETUP INSTRUCTIONS
# ─────────────────────────────────────────────────────
#
# For TypeDoc (TypeScript projects):
# 1. npm install -D typedoc typedoc-plugin-markdown
# 2. Create typedoc.json:
#    {
#      "entryPoints": ["src/index.ts"],
#      "out": "docs-dist",
#      "plugin": ["typedoc-plugin-markdown"],
#      "readme": "README.md"
#    }
#
# For OpenAPI (REST APIs):
# 1. Create openapi.yaml in project root
# 2. Redocly is used automatically (no local install needed)
#
# For Sphinx (Python projects):
# 1. Create docs/ directory with conf.py
# 2. Add docs/requirements.txt with sphinx dependencies
#
# Enable GitHub Pages:
# 1. Go to Settings > Pages
# 2. Source: GitHub Actions
#
# ─────────────────────────────────────────────────────
