# Auto Labeler Workflow
#
# Automatically labels pull requests based on conventional commit prefixes in
# the PR title. This removes manual labeling work and ensures consistent
# categorization of changes.
#
# Mapping:
#   feat:     -> enhancement
#   fix:      -> bug
#   docs:     -> documentation
#   chore:    -> chore
#   ci:       -> github-actions
#   test:     -> testing
#   refactor: -> refactor
#   perf:     -> performance
#   style:    -> style
#   build:    -> build
#   revert:   -> revert
#
# Also labels PRs based on changed file paths (optional).
#
# PREREQUISITES:
# 1. Labels must exist in the repository. Create them with:
#    gh label create "enhancement" -c "a2eeef" -d "New feature or request"
#    gh label create "bug" -c "d73a4a" -d "Something isn't working"
#    gh label create "documentation" -c "0075ca" -d "Documentation improvements"
#    gh label create "chore" -c "fef2c0" -d "Maintenance tasks"
#    gh label create "github-actions" -c "000000" -d "CI/CD changes"
#    gh label create "testing" -c "bfd4f2" -d "Test improvements"
#    gh label create "refactor" -c "d4c5f9" -d "Code refactoring"
#    gh label create "performance" -c "f9d0c4" -d "Performance improvements"
#    gh label create "dependencies" -c "0366d6" -d "Dependency updates"

name: Auto Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on conventional commit prefix
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const labels = [];

            // Conventional commit type to label mapping
            const conventionalLabels = {
              'feat': 'enhancement',
              'fix': 'bug',
              'docs': 'documentation',
              'chore': 'chore',
              'ci': 'github-actions',
              'test': 'testing',
              'refactor': 'refactor',
              'perf': 'performance',
              'style': 'style',
              'build': 'build',
              'revert': 'revert'
            };

            // Check for conventional commit prefix
            const match = title.match(/^(\w+)(\(.+\))?!?:/);
            if (match) {
              const type = match[1].toLowerCase();
              if (conventionalLabels[type]) {
                labels.push(conventionalLabels[type]);
              }

              // Check for breaking change indicator
              if (title.includes('!:') || title.toLowerCase().includes('breaking')) {
                labels.push('breaking-change');
              }
            }

            // Add labels if any were determined
            if (labels.length > 0) {
              try {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  labels: labels
                });
                console.log(`Added labels: ${labels.join(', ')}`);
              } catch (error) {
                // Label might not exist - log but don't fail
                console.log(`Could not add labels: ${error.message}`);
                console.log('Ensure labels exist in the repository.');
              }
            } else {
              console.log('No conventional commit prefix detected in PR title.');
            }

      # Optional: Label based on changed files
      - name: Label PR based on file paths
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: false
        continue-on-error: true

# Optional: Create .github/labeler.yml for path-based labeling
# Example .github/labeler.yml:
# ---
# documentation:
#   - changed-files:
#       - any-glob-to-any-file:
#           - '**/*.md'
#           - 'docs/**'
#
# dependencies:
#   - changed-files:
#       - any-glob-to-any-file:
#           - 'package.json'
#           - 'package-lock.json'
#           - 'yarn.lock'
#           - 'pnpm-lock.yaml'
#           - 'requirements.txt'
#           - 'Pipfile.lock'
#           - 'Cargo.lock'
#           - 'go.sum'
#
# github-actions:
#   - changed-files:
#       - any-glob-to-any-file:
#           - '.github/workflows/**'
#           - '.github/actions/**'
#
# frontend:
#   - changed-files:
#       - any-glob-to-any-file:
#           - 'src/components/**'
#           - 'src/pages/**'
#           - '**/*.tsx'
#           - '**/*.css'
#           - '**/*.scss'
#
# backend:
#   - changed-files:
#       - any-glob-to-any-file:
#           - 'src/api/**'
#           - 'src/services/**'
#           - 'src/controllers/**'
#
# tests:
#   - changed-files:
#       - any-glob-to-any-file:
#           - '**/*.test.*'
#           - '**/*.spec.*'
#           - 'tests/**'
#           - '__tests__/**'
