# C/C++ CI Workflow
# Builds and tests C/C++ projects using CMake.
#
# Features:
# - Multi-compiler matrix (GCC, Clang)
# - Multi-platform support (Linux, macOS, Windows)
# - CMake presets support
# - Sanitizer builds (ASan, UBSan)
# - Code coverage with lcov
# - Caching for faster builds
#
# Build systems supported:
# - CMake (default)
# - Meson (alternative)
# - Make (alternative)
#
# Documentation:
# - https://cmake.org/documentation/
# - https://clang.llvm.org/docs/AddressSanitizer.html

name: C/C++ CI

on:
  push:
    branches:
      - main
    paths:
      - "**.c"
      - "**.cc"
      - "**.cpp"
      - "**.cxx"
      - "**.h"
      - "**.hpp"
      - "**.hxx"
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/ci-cpp.yml"
  pull_request:
    paths:
      - "**.c"
      - "**.cc"
      - "**.cpp"
      - "**.cxx"
      - "**.h"
      - "**.hpp"
      - "**.hxx"
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/ci-cpp.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux with GCC
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc-13
            cxx: g++-13

          # Linux with Clang
          - os: ubuntu-latest
            compiler: clang
            cc: clang-17
            cxx: clang++-17

          # macOS with Apple Clang
          - os: macos-latest
            compiler: appleclang
            cc: clang
            cxx: clang++

          # Windows with MSVC
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Linux: Install compilers
      - name: Install GCC (Linux)
        if: runner.os == 'Linux' && matrix.compiler == 'gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13

      - name: Install Clang (Linux)
        if: runner.os == 'Linux' && matrix.compiler == 'clang'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17

      # Setup build tools
      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      # Cache
      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-${{ matrix.compiler }}-cmake-${{ hashFiles('CMakeLists.txt', 'cmake/**') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-cmake-

      # Configure
      - name: Configure (Unix)
        if: runner.os != 'Windows'
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64

      # Build
      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      # Test
      - name: Run tests
        run: ctest --test-dir build --build-config ${{ env.BUILD_TYPE }} --output-on-failure

  # Sanitizer builds (Linux only)
  sanitizers:
    name: Sanitizers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined, thread]
        # Note: memory sanitizer requires instrumented libc++

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Configure with ${{ matrix.sanitizer }} sanitizer
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=clang-17 \
            -DCMAKE_CXX_COMPILER=clang++-17 \
            -DCMAKE_C_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer" \
            -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=${{ matrix.sanitizer }}" \
            -DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=${{ matrix.sanitizer }}"

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
        env:
          ASAN_OPTIONS: detect_leaks=1:strict_string_checks=1
          UBSAN_OPTIONS: print_stacktrace=1
          TSAN_OPTIONS: second_deadlock_stack=1

  # Code coverage
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    if: false # Enable when coverage is configured

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Configure with coverage
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_FLAGS="--coverage" \
            -DCMAKE_CXX_FLAGS="--coverage"

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Generate coverage report
        run: |
          lcov --capture --directory build --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.info
          fail_ci_if_error: true
