name: CI (Foundry)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Build & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check Solidity formatting
        run: forge fmt --check

      - name: Build contracts
        run: forge build --sizes
        id: build

      # Check contract sizes don't exceed 24KB limit
      - name: Check contract sizes
        run: |
          forge build --sizes 2>&1 | tee sizes.txt
          if grep -q "is above the size limit" sizes.txt; then
            echo "::error::Contract size exceeds 24KB limit"
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv
        env:
          # Fork testing (uncomment and add secrets if needed)
          # MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          # SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          FOUNDRY_PROFILE: ci

      - name: Run tests with gas report
        run: forge test --gas-report
        env:
          FOUNDRY_PROFILE: ci

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate coverage report
        run: forge coverage --report lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: false

  fuzz:
    name: Fuzz Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run fuzz tests
        run: forge test --match-test "testFuzz" -vvv
        env:
          FOUNDRY_FUZZ_RUNS: 1000
          FOUNDRY_PROFILE: ci

  invariant:
    name: Invariant Testing
    runs-on: ubuntu-latest
    # Invariant tests can be slow - only run on main or when requested
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run-invariants')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run invariant tests
        run: forge test --match-test "invariant" -vvv
        env:
          FOUNDRY_INVARIANT_RUNS: 256
          FOUNDRY_INVARIANT_DEPTH: 32
          FOUNDRY_PROFILE: ci

  security:
    name: Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Slither
        run: pip install slither-analyzer solc-select

      - name: Install Solidity compiler
        run: |
          solc-select install 0.8.20
          solc-select use 0.8.20

      - name: Run Slither
        run: slither . --config-file slither.config.json
        continue-on-error: true

  snapshot:
    name: Gas Snapshot
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate gas snapshot
        run: forge snapshot

      - name: Compare gas snapshot
        run: forge snapshot --check
        continue-on-error: true

      - name: Upload snapshot diff
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            let snapshot = '';

            try {
              snapshot = fs.readFileSync('.gas-snapshot', 'utf8');
            } catch {
              snapshot = 'Gas snapshot not generated.';
            }

            const body = `## ⛽ Gas Snapshot\n\n\`\`\`\n${snapshot.substring(0, 60000)}\n\`\`\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
