# Godot CI Workflow
# Build and export Godot 4.x projects for multiple platforms
#
# Features:
#   - Godot 4.x engine exports
#   - Multi-platform builds (Windows, Linux, macOS, Web, Android)
#   - Asset validation
#   - GDScript linting with gdlint
#   - Artifact upload for each platform
#
# Prerequisites:
#   1. Godot project with export presets configured
#   2. Export templates installed (workflow handles this)
#   3. For Android: keystore secrets configured
#
# Required secrets (for Android):
#   GODOT_ANDROID_KEYSTORE_BASE64 - Base64-encoded keystore file
#   GODOT_ANDROID_KEYSTORE_PASSWORD - Keystore password
#   GODOT_ANDROID_KEY_ALIAS - Key alias
#   GODOT_ANDROID_KEY_PASSWORD - Key password
#
# Customization:
#   - Adjust GODOT_VERSION for your project
#   - Enable/disable platforms by uncommenting jobs
#   - Modify export preset names to match your project

name: CI (Godot)

on:
  push:
    branches: [main]
    paths:
      - '**.gd'
      - '**.tscn'
      - '**.tres'
      - '**.gdshader'
      - 'project.godot'
      - 'export_presets.cfg'
      - '.github/workflows/ci-godot.yml'
  pull_request:
    branches: [main]

env:
  GODOT_VERSION: "4.2.2"
  EXPORT_NAME: game

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # GDScript linting
  lint:
    name: GDScript Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install gdlint
        run: pip install gdtoolkit

      - name: Run GDScript linter
        run: gdlint **/*.gd
        continue-on-error: true

  # Validate project structure
  validate:
    name: Validate Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check project.godot exists
        run: |
          if [ ! -f "project.godot" ]; then
            echo "Error: project.godot not found"
            exit 1
          fi
          echo "Project file found"

      - name: Check export presets
        run: |
          if [ ! -f "export_presets.cfg" ]; then
            echo "Warning: export_presets.cfg not found - exports may fail"
          else
            echo "Export presets found"
          fi

  # Linux export
  export-linux:
    name: Export (Linux)
    runs-on: ubuntu-latest
    needs: [lint, validate]
    container:
      image: barichello/godot-ci:${{ env.GODOT_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Create build directory
        run: mkdir -v -p build/linux

      - name: Export for Linux
        run: godot --headless --verbose --export-release "Linux/X11" build/linux/${{ env.EXPORT_NAME }}.x86_64

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-linux
          path: build/linux/
          retention-days: 14

  # Windows export
  export-windows:
    name: Export (Windows)
    runs-on: ubuntu-latest
    needs: [lint, validate]
    container:
      image: barichello/godot-ci:${{ env.GODOT_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Create build directory
        run: mkdir -v -p build/windows

      - name: Export for Windows
        run: godot --headless --verbose --export-release "Windows Desktop" build/windows/${{ env.EXPORT_NAME }}.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-windows
          path: build/windows/
          retention-days: 14

  # macOS export
  export-macos:
    name: Export (macOS)
    runs-on: ubuntu-latest
    needs: [lint, validate]
    container:
      image: barichello/godot-ci:${{ env.GODOT_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Create build directory
        run: mkdir -v -p build/macos

      - name: Export for macOS
        run: godot --headless --verbose --export-release "macOS" build/macos/${{ env.EXPORT_NAME }}.zip

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-macos
          path: build/macos/
          retention-days: 14

  # Web export
  export-web:
    name: Export (Web)
    runs-on: ubuntu-latest
    needs: [lint, validate]
    container:
      image: barichello/godot-ci:${{ env.GODOT_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Create build directory
        run: mkdir -v -p build/web

      - name: Export for Web
        run: godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-web
          path: build/web/
          retention-days: 14

  # Optional: Android export (uncomment to enable)
  # export-android:
  #   name: Export (Android)
  #   runs-on: ubuntu-latest
  #   needs: [lint, validate]
  #   container:
  #     image: barichello/godot-ci:${{ env.GODOT_VERSION }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         lfs: true
  #
  #     - name: Setup export templates
  #       run: |
  #         mkdir -v -p ~/.local/share/godot/export_templates/
  #         mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
  #
  #     - name: Setup Android SDK
  #       run: |
  #         echo "Setting up Android SDK..."
  #         # Android SDK is pre-installed in the container
  #
  #     - name: Setup keystore
  #       run: |
  #         echo "${{ secrets.GODOT_ANDROID_KEYSTORE_BASE64 }}" | base64 -d > release.keystore
  #
  #     - name: Create build directory
  #       run: mkdir -v -p build/android
  #
  #     - name: Export for Android
  #       env:
  #         GODOT_ANDROID_KEYSTORE_RELEASE_PATH: release.keystore
  #         GODOT_ANDROID_KEYSTORE_RELEASE_USER: ${{ secrets.GODOT_ANDROID_KEY_ALIAS }}
  #         GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: ${{ secrets.GODOT_ANDROID_KEYSTORE_PASSWORD }}
  #       run: godot --headless --verbose --export-release "Android" build/android/${{ env.EXPORT_NAME }}.apk
  #
  #     - name: Upload Android artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ env.EXPORT_NAME }}-android
  #         path: build/android/
  #         retention-days: 14
