name: CI (Hardhat)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint Solidity (Solhint)
        run: npm run lint:sol --if-present

      - name: Lint TypeScript/JavaScript
        run: npm run lint --if-present

      - name: Check formatting (Prettier)
        run: npm run format:check --if-present

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test
        env:
          REPORT_GAS: true

      - name: Generate coverage report
        run: npx hardhat coverage
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

  security:
    name: Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither
        run: slither . --config-file slither.config.json || true
        continue-on-error: true

      # Optional: Mythril (comment out if not needed - slower but thorough)
      # - name: Install Mythril
      #   run: pip install mythril
      #
      # - name: Run Mythril
      #   run: myth analyze contracts/*.sol --execution-timeout 300
      #   continue-on-error: true

  gas-report:
    name: Gas Report
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with gas report
        run: npx hardhat test
        env:
          REPORT_GAS: true

      # Comment on PR with gas report (requires hardhat-gas-reporter output)
      - name: Comment gas report
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            let gasReport = '';

            // Check if gas report file exists (depends on hardhat-gas-reporter config)
            try {
              gasReport = fs.readFileSync('gas-report.txt', 'utf8');
            } catch {
              gasReport = 'Gas report not generated. Ensure hardhat-gas-reporter is configured.';
            }

            const body = `## ⛽ Gas Report\n\n\`\`\`\n${gasReport}\n\`\`\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body.substring(0, 65536) // GitHub comment limit
            });

  size-check:
    name: Contract Size Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check contract sizes
        run: npx hardhat size-contracts
        continue-on-error: true
