# iOS CI Workflow
#
# Builds iOS app using xcodebuild and runs tests.
# Supports both unit tests and UI tests.
#
# Features:
#   - Swift Package Manager caching
#   - Matrix builds for multiple iOS versions
#   - Simulator-based testing
#   - Test result reporting

name: CI (iOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Update these to match your project
  SCHEME: 'YourApp'
  PROJECT: 'YourApp.xcodeproj'
  # Or use workspace for CocoaPods/SPM
  # WORKSPACE: 'YourApp.xcworkspace'

jobs:
  build-and-test:
    name: Build & Test (iOS ${{ matrix.ios-version }})
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        ios-version: ['17.2', '17.5']
        include:
          - ios-version: '17.2'
            device: 'iPhone 15'
          - ios-version: '17.5'
            device: 'iPhone 15 Pro'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # Uncomment if using CocoaPods
      # - name: Cache CocoaPods
      #   uses: actions/cache@v4
      #   with:
      #     path: Pods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-
      #
      # - name: Install CocoaPods dependencies
      #   run: pod install

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -project ${{ env.PROJECT }} \
            -scheme ${{ env.SCHEME }} \
            -destination "platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios-version }}" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty

      - name: Run unit tests
        run: |
          xcodebuild test-without-building \
            -project ${{ env.PROJECT }} \
            -scheme ${{ env.SCHEME }} \
            -destination "platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios-version }}" \
            -configuration Debug \
            -resultBundlePath TestResults.xcresult \
            | xcpretty

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-ios-${{ matrix.ios-version }}
          path: TestResults.xcresult
          retention-days: 7

  # SwiftLint check
  lint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  # Optional: UI Tests (separate job for longer-running tests)
  # ui-tests:
  #   name: UI Tests
  #   runs-on: macos-14
  #   needs: build-and-test
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Select Xcode version
  #       run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
  #
  #     - name: Run UI tests
  #       run: |
  #         xcodebuild test \
  #           -project ${{ env.PROJECT }} \
  #           -scheme ${{ env.SCHEME }}UITests \
  #           -destination "platform=iOS Simulator,name=iPhone 15,OS=17.2" \
  #           -configuration Debug \
  #           CODE_SIGNING_ALLOWED=NO \
  #           | xcpretty

  # Optional: Archive for distribution
  # archive:
  #   name: Archive
  #   runs-on: macos-14
  #   needs: [build-and-test, lint]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Select Xcode version
  #       run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
  #
  #     - name: Install Apple certificate and provisioning profile
  #       env:
  #         CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
  #         P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  #         PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
  #         KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  #       run: |
  #         # Create variables
  #         CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
  #         PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
  #         KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
  #
  #         # Import certificate and provisioning profile
  #         echo -n "$CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
  #         echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PP_PATH
  #
  #         # Create temporary keychain
  #         security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
  #         security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
  #         security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
  #
  #         # Import certificate to keychain
  #         security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
  #         security list-keychain -d user -s $KEYCHAIN_PATH
  #
  #         # Apply provisioning profile
  #         mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  #         cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
  #
  #     - name: Archive app
  #       run: |
  #         xcodebuild archive \
  #           -project ${{ env.PROJECT }} \
  #           -scheme ${{ env.SCHEME }} \
  #           -archivePath $RUNNER_TEMP/YourApp.xcarchive \
  #           -configuration Release
  #
  #     - name: Export IPA
  #       run: |
  #         xcodebuild -exportArchive \
  #           -archivePath $RUNNER_TEMP/YourApp.xcarchive \
  #           -exportOptionsPlist ExportOptions.plist \
  #           -exportPath $RUNNER_TEMP/export
  #
  #     - name: Upload IPA
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: app-ipa
  #         path: ${{ runner.temp }}/export/*.ipa
  #         retention-days: 30
