name: CI (Java)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test (Java ${{ matrix.java }}, ${{ matrix.build-tool }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']
        build-tool: ['maven']
        # Uncomment to also test with Gradle:
        # build-tool: ['maven', 'gradle']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: ${{ matrix.build-tool }}

      # Maven build steps
      - name: Build with Maven
        if: matrix.build-tool == 'maven'
        run: mvn -B verify --file pom.xml

      - name: Run tests with Maven
        if: matrix.build-tool == 'maven'
        run: mvn -B test --file pom.xml

      # Gradle build steps
      - name: Build with Gradle
        if: matrix.build-tool == 'gradle'
        run: ./gradlew build

      - name: Run tests with Gradle
        if: matrix.build-tool == 'gradle'
        run: ./gradlew test

  # Optional: Upload coverage to Codecov
  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with:
  #         java-version: '21'
  #         distribution: 'temurin'
  #         cache: 'maven'
  #     - run: mvn -B verify --file pom.xml -Pcoverage
  #     - uses: codecov/codecov-action@v4
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         fail_ci_if_error: false
