name: CI (Ruby)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test (Ruby ${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2', '3.3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop linter
        run: bundle exec rubocop --parallel
        continue-on-error: true

      - name: Run tests with RSpec
        run: bundle exec rspec
        continue-on-error: true

      # Alternative: Run tests with Minitest
      # - name: Run tests with Minitest
      #   run: bundle exec rake test

      - name: Run tests with Rake (fallback)
        run: bundle exec rake test --trace 2>/dev/null || bundle exec rake 2>/dev/null || true
        continue-on-error: true

  # Optional: Upload coverage to Codecov
  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.3'
  #         bundler-cache: true
  #     - run: bundle install
  #     - run: bundle exec rspec --format documentation
  #       env:
  #         COVERAGE: true
  #     - uses: codecov/codecov-action@v4
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         fail_ci_if_error: false
