name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-language:
    name: Detect Project Language
    runs-on: ubuntu-latest
    outputs:
      nodejs: ${{ steps.detect.outputs.nodejs }}
      python: ${{ steps.detect.outputs.python }}
      go: ${{ steps.detect.outputs.go }}
      rust: ${{ steps.detect.outputs.rust }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect languages
        id: detect
        run: |
          echo "nodejs=$([[ -f package.json ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "python=$([[ -f pyproject.toml || -f requirements.txt || -f setup.py ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "go=$([[ -f go.mod ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "rust=$([[ -f Cargo.toml ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

  coverage-nodejs:
    name: Coverage (Node.js)
    runs-on: ubuntu-latest
    needs: detect-language
    if: needs.detect-language.outputs.nodejs == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Run tests with coverage
        run: npm run test:coverage --if-present || npm test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: nodejs
          fail_ci_if_error: false

  coverage-python:
    name: Coverage (Python)
    runs-on: ubuntu-latest
    needs: detect-language
    if: needs.detect-language.outputs.python == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -e ".[dev]" 2>/dev/null || pip install -r requirements.txt 2>/dev/null || true
      - name: Run tests with coverage
        run: pytest --cov --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: python
          fail_ci_if_error: false

  coverage-go:
    name: Coverage (Go)
    runs-on: ubuntu-latest
    needs: detect-language
    if: needs.detect-language.outputs.go == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: go
          fail_ci_if_error: false

  coverage-rust:
    name: Coverage (Rust)
    runs-on: ubuntu-latest
    needs: detect-language
    if: needs.detect-language.outputs.rust == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Generate coverage
        run: cargo tarpaulin --out xml --output-dir ./coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/cobertura.xml
          flags: rust
          fail_ci_if_error: false
