name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on high and critical vulnerabilities
          fail-on-severity: high
          # Comment on PR with vulnerabilities found
          comment-summary-in-pr: always
          # Deny specific licenses (uncomment to enable)
          # deny-licenses: GPL-3.0, AGPL-3.0
          # Allow specific licenses only (uncomment to enable)
          # allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
