# Azure App Service Deployment
# Deploys applications to Azure App Service (Web Apps).
#
# Prerequisites:
# 1. Create Azure App Service resource
# 2. Configure authentication (recommended: OIDC federated credentials)
# 3. Set required secrets/variables
#
# Required secrets:
#   AZURE_CLIENT_ID        - Azure AD application (client) ID
#   AZURE_TENANT_ID        - Azure AD tenant ID
#   AZURE_SUBSCRIPTION_ID  - Azure subscription ID
#   AZURE_WEBAPP_NAME      - Name of the App Service
#
# Authentication options:
# - OIDC (recommended): No secrets to manage, uses federated credentials
# - Service Principal: Uses AZURE_CREDENTIALS secret (JSON)
# - Publish Profile: Uses AZURE_WEBAPP_PUBLISH_PROFILE
#
# Documentation:
# - https://learn.microsoft.com/azure/app-service/
# - https://github.com/Azure/webapps-deploy

name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME || 'your-app-name' }}
  AZURE_WEBAPP_SLOT: ${{ github.event.inputs.environment == 'staging' && 'staging' || 'production' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node.js example
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            dist/
            package.json
            package-lock.json
          retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: .

      # Option 1: OIDC Authentication (Recommended)
      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Option 2: Service Principal (Alternative)
      # - name: Login to Azure (Service Principal)
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          package: .

      # Option 3: Publish Profile (Simplest, no Azure CLI needed)
      # - name: Deploy using Publish Profile
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: .

      - name: Logout from Azure
        if: always()
        run: az logout

  # Optional: Swap staging slot to production
  swap-slots:
    name: Swap Slots
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.inputs.environment == 'staging'
    environment:
      name: production

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Swap staging to production
        run: |
          az webapp deployment slot swap \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --slot staging \
            --target-slot production

      - name: Logout from Azure
        if: always()
        run: az logout
