name: Deploy to Kubernetes

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
      image_digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update image in manifests
        run: |
          cd k8s
          kustomize edit set image app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build.outputs.image_digest }}

      - name: Deploy with kubectl
        run: |
          kubectl apply -k k8s/
          kubectl rollout status deployment/app -n default --timeout=300s

      - name: Verify deployment
        run: |
          kubectl get pods -l app=app -n default
          kubectl get services -l app=app -n default

  # Alternative: Deploy with Helm
  # deploy-helm:
  #   name: Deploy with Helm
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: production
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: azure/setup-helm@v4
  #     - name: Configure kubeconfig
  #       run: |
  #         mkdir -p ~/.kube
  #         echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
  #     - name: Deploy with Helm
  #       run: |
  #         helm upgrade --install app ./helm/app \
  #           --namespace default \
  #           --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
  #           --set image.tag=${{ github.sha }} \
  #           --wait --timeout 5m

  # Alternative: Deploy to EKS
  # deploy-eks:
  #   name: Deploy to EKS
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: production
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
  #         aws-region: us-east-1
  #     - run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
  #     - run: kubectl apply -k k8s/

  # Alternative: Deploy to GKE
  # deploy-gke:
  #   name: Deploy to GKE
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: production
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: google-github-actions/auth@v2
  #       with:
  #         workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  #         service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  #     - uses: google-github-actions/get-gke-credentials@v2
  #       with:
  #         cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
  #         location: ${{ secrets.GKE_CLUSTER_LOCATION }}
  #     - run: kubectl apply -k k8s/

# Required secrets:
# - KUBE_CONFIG: Base64-encoded kubeconfig file
#
# For EKS:
# - AWS_ROLE_ARN: IAM role ARN for OIDC
# - EKS_CLUSTER_NAME: EKS cluster name
#
# For GKE:
# - GCP_WORKLOAD_IDENTITY_PROVIDER: Workload identity provider
# - GCP_SERVICE_ACCOUNT: Service account email
# - GKE_CLUSTER_NAME: GKE cluster name
# - GKE_CLUSTER_LOCATION: Cluster location (zone or region)
