# Google Cloud Run Deployment
# Deploys containerized applications to Cloud Run (serverless containers).
#
# Prerequisites:
# 1. Enable Cloud Run API in your GCP project
# 2. Create Artifact Registry repository (or use Container Registry)
# 3. Set up Workload Identity Federation (OIDC) - recommended
#
# Required secrets:
#   GCP_PROJECT_ID         - Google Cloud project ID
#   GCP_WORKLOAD_IDENTITY_PROVIDER - Workload Identity Provider
#   GCP_SERVICE_ACCOUNT    - Service account email for deployments
#
# Required variables:
#   GCP_REGION             - Deployment region (e.g., us-central1)
#   CLOUD_RUN_SERVICE      - Cloud Run service name
#
# Documentation:
# - https://cloud.google.com/run/docs
# - https://github.com/google-github-actions/deploy-cloudrun

name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION || 'us-central1' }}
  CLOUD_RUN_SERVICE: ${{ vars.CLOUD_RUN_SERVICE || 'my-service' }}
  # Artifact Registry path
  GAR_LOCATION: ${{ vars.GCP_REGION || 'us-central1' }}
  GAR_REPOSITORY: ${{ vars.GAR_REPOSITORY || 'docker-repo' }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate using Workload Identity Federation (OIDC)
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image tag
        id: tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE }}"
          echo "image=${IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "latest=${IMAGE}:latest" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.tag.outputs.image }}
            ${{ steps.tag.outputs.latest }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image
        run: echo "image=${{ steps.tag.outputs.image }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.CLOUD_RUN_SERVICE }}
          region: ${{ env.GCP_REGION }}
          image: ${{ needs.build.outputs.image }}
          # Optional configurations
          flags: |
            --allow-unauthenticated
            --memory=512Mi
            --cpu=1
            --min-instances=0
            --max-instances=10
            --concurrency=80

      - name: Summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Service:** ${{ env.CLOUD_RUN_SERVICE }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Region:** ${{ env.GCP_REGION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **URL:** ${{ steps.deploy.outputs.url }}" >> $GITHUB_STEP_SUMMARY

  # Optional: Traffic management for gradual rollouts
  # traffic:
  #   name: Manage Traffic
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   if: false  # Enable for gradual rollouts
  #
  #   steps:
  #     - name: Authenticate
  #       uses: google-github-actions/auth@v2
  #       with:
  #         workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  #         service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  #
  #     - name: Gradual rollout
  #       run: |
  #         gcloud run services update-traffic ${{ env.CLOUD_RUN_SERVICE }} \
  #           --region=${{ env.GCP_REGION }} \
  #           --to-latest=50
