name: Deploy to Render

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

      # Alternative: Use Render API for more control
      # - name: Deploy via API
      #   run: |
      #     curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
      #       -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{"clearCache": "do_not_clear"}'

  # Alternative: Wait for deployment to complete
  # deploy-and-wait:
  #   name: Deploy and Wait
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - name: Trigger deploy
  #       id: deploy
  #       run: |
  #         RESPONSE=$(curl -s -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
  #           -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
  #           -H "Content-Type: application/json" \
  #           -d '{"clearCache": "do_not_clear"}')
  #         DEPLOY_ID=$(echo $RESPONSE | jq -r '.id')
  #         echo "deploy_id=$DEPLOY_ID" >> $GITHUB_OUTPUT
  #
  #     - name: Wait for deployment
  #       run: |
  #         DEPLOY_ID="${{ steps.deploy.outputs.deploy_id }}"
  #         for i in {1..60}; do
  #           STATUS=$(curl -s "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID" \
  #             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" | jq -r '.status')
  #           echo "Deploy status: $STATUS"
  #           if [ "$STATUS" = "live" ]; then
  #             echo "Deployment successful!"
  #             exit 0
  #           elif [ "$STATUS" = "deactivated" ] || [ "$STATUS" = "build_failed" ]; then
  #             echo "Deployment failed!"
  #             exit 1
  #           fi
  #           sleep 10
  #         done
  #         echo "Deployment timed out"
  #         exit 1

# Required secrets:
# - RENDER_DEPLOY_HOOK_URL: Deploy hook URL from Render dashboard
#
# For API-based deployment:
# - RENDER_API_KEY: Render API key (generate at render.com/docs/api)
# - RENDER_SERVICE_ID: Service ID (found in service URL: srv-xxxxx)
#
# Getting Deploy Hook URL:
# 1. Go to your Render service dashboard
# 2. Click "Settings"
# 3. Scroll to "Deploy Hook"
# 4. Copy the URL
#
# render.yaml (optional, for Infrastructure as Code):
# services:
#   - type: web
#     name: my-app
#     runtime: node
#     plan: free
#     buildCommand: npm install && npm run build
#     startCommand: npm start
#     healthCheckPath: /health
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: DATABASE_URL
#         fromDatabase:
#           name: my-db
#           property: connectionString
#
# databases:
#   - name: my-db
#     plan: free
#     databaseName: myapp
#     user: myapp
