name: Lighthouse Performance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

      # Alternative: Run against deployed URL
      # - name: Run Lighthouse CI (URL)
      #   uses: treosh/lighthouse-ci-action@v12
      #   with:
      #     urls: |
      #       https://example.com
      #       https://example.com/about
      #     uploadArtifacts: true
      #     temporaryPublicStorage: true

  # Optional: Lighthouse with budget assertions
  # lighthouse-budget:
  #   name: Lighthouse Budget Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run build
  #     - uses: treosh/lighthouse-ci-action@v12
  #       with:
  #         budgetPath: './budget.json'
  #         uploadArtifacts: true

# Example lighthouserc.json configuration:
# {
#   "ci": {
#     "collect": {
#       "startServerCommand": "npm run start",
#       "startServerReadyPattern": "ready on",
#       "url": ["http://localhost:3000"],
#       "numberOfRuns": 3
#     },
#     "assert": {
#       "preset": "lighthouse:recommended",
#       "assertions": {
#         "categories:performance": ["warn", { "minScore": 0.9 }],
#         "categories:accessibility": ["error", { "minScore": 0.9 }],
#         "categories:best-practices": ["warn", { "minScore": 0.9 }],
#         "categories:seo": ["warn", { "minScore": 0.9 }]
#       }
#     },
#     "upload": {
#       "target": "temporary-public-storage"
#     }
#   }
# }

# Example budget.json for performance budgets:
# [
#   {
#     "path": "/*",
#     "timings": [
#       { "metric": "first-contentful-paint", "budget": 2000 },
#       { "metric": "interactive", "budget": 5000 },
#       { "metric": "largest-contentful-paint", "budget": 2500 }
#     ],
#     "resourceSizes": [
#       { "resourceType": "script", "budget": 300 },
#       { "resourceType": "total", "budget": 500 }
#     ]
#   }
# ]
