name: Check Links

on:
  push:
    branches: [main]
    paths:
      - '**.md'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
  schedule:
    # Run weekly on Sundays at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links with Lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose
            --no-progress
            --accept 100..=103,200..=299,403,429
            --exclude-mail
            --exclude "localhost"
            --exclude "127.0.0.1"
            '**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue on Failure
        if: failure() && github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Link Checker: Broken links detected"
          content-filepath: ./lychee/out.md
          labels: bug, automated
