# NuGet Package Publishing
# Publishes .NET packages to NuGet.org on release.
#
# Prerequisites:
# 1. Create NuGet.org account
# 2. Generate API key at https://www.nuget.org/account/apikeys
# 3. Add NUGET_API_KEY secret
#
# Required secrets:
#   NUGET_API_KEY - NuGet.org API key with push permissions
#
# Package configuration:
# - Version is read from .csproj or Directory.Build.props
# - Package metadata from .csproj (PackageId, Description, etc.)
#
# Documentation:
# - https://learn.microsoft.com/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli
# - https://docs.github.com/actions/publishing-packages/publishing-dotnet-packages

name: Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (without 'v' prefix)"
        required: true
        type: string

permissions:
  contents: read

env:
  DOTNET_VERSION: "8.0.x"
  NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
  # Project path (adjust if your project is in a subdirectory)
  PROJECT_PATH: "src/YourProject/YourProject.csproj"

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            # Remove 'v' prefix if present
            VERSION="${VERSION#v}"
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore \
            /p:Version=${{ steps.version.outputs.version }}

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack
        run: |
          dotnet pack --configuration Release --no-build \
            /p:Version=${{ steps.version.outputs.version }} \
            --output ./nupkgs

      - name: List packages
        run: ls -la ./nupkgs/

      - name: Verify package version
        run: |
          PACKAGE_VERSION=$(ls ./nupkgs/*.nupkg | head -1 | grep -oP '\d+\.\d+\.\d+(-[\w.]+)?')
          echo "Package version: $PACKAGE_VERSION"
          if [ "$PACKAGE_VERSION" != "${{ steps.version.outputs.version }}" ]; then
            echo "::warning::Package version ($PACKAGE_VERSION) doesn't match release (${{ steps.version.outputs.version }})"
          fi

      - name: Push to NuGet
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source ${{ env.NUGET_SOURCE }} \
            --skip-duplicate

      # Optional: Also publish to GitHub Packages
      # - name: Push to GitHub Packages
      #   run: |
      #     dotnet nuget add source \
      #       --username ${{ github.actor }} \
      #       --password ${{ secrets.GITHUB_TOKEN }} \
      #       --store-password-in-clear-text \
      #       --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      #
      #     dotnet nuget push ./nupkgs/*.nupkg \
      #       --source "github" \
      #       --skip-duplicate

      - name: Summary
        run: |
          echo "## NuGet Publishing Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Packages:**" >> $GITHUB_STEP_SUMMARY
          for pkg in ./nupkgs/*.nupkg; do
            echo "  - $(basename $pkg)" >> $GITHUB_STEP_SUMMARY
          done

  # Optional: Publish symbols package
  publish-symbols:
    name: Publish Symbols
    runs-on: ubuntu-latest
    needs: publish
    if: false # Enable if using symbol packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with symbols
        run: |
          dotnet pack --configuration Release \
            /p:IncludeSymbols=true \
            /p:SymbolPackageFormat=snupkg \
            --output ./nupkgs

      - name: Push symbols
        run: |
          dotnet nuget push ./nupkgs/*.snupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source ${{ env.NUGET_SOURCE }} \
            --skip-duplicate
