# Publish Docker Image to Docker Hub
# Builds and pushes container images to Docker Hub
#
# Features:
#   - Multi-architecture builds (amd64, arm64)
#   - Build caching with GitHub Actions cache
#   - Automatic README sync
#   - Image attestation
#
# Required secrets:
#   DOCKERHUB_USERNAME - Docker Hub username
#   DOCKERHUB_TOKEN - Docker Hub access token (not password)
#
# Setup:
#   1. Create Docker Hub access token: https://hub.docker.com/settings/security
#   2. Add secrets to repository settings
#   3. Optionally set DOCKERHUB_REPOSITORY variable (defaults to repo name)

name: Publish to Docker Hub

on:
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'src/**'
      - '.github/workflows/publish-docker-hub.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY || github.event.repository.name }}

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    outputs:
      image: ${{ steps.output.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Output image URI
        id: output
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}"
          echo "Image: $IMAGE"
          echo "Digest: ${{ steps.build.outputs.digest }}"
          echo "image=$IMAGE@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  # Optional: Sync README to Docker Hub
  sync-readme:
    name: Sync README
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync README to Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}

# Docker Hub Access Token Setup:
#
# 1. Go to https://hub.docker.com/settings/security
# 2. Click "New Access Token"
# 3. Name: "GitHub Actions - <repo-name>"
# 4. Access permissions: Read, Write, Delete (or Read & Write for publish only)
# 5. Copy the token and add as DOCKERHUB_TOKEN secret
#
# Best Practices:
#   - Use access tokens, not passwords
#   - Create separate tokens per repository
#   - Use minimal required permissions
#   - Rotate tokens periodically
