name: Publish Electron App

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.2.3)'
        required: true
        type: string
      draft:
        description: 'Create as draft release'
        required: false
        type: boolean
        default: false

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION"

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: get-version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Update version
        run: npm version ${{ needs.get-version.outputs.version }} --no-git-tag-version

      - name: Build app
        run: npm run build

      - name: Build Linux packages
        run: |
          npx electron-builder --linux \
            --x64 --arm64 \
            -p never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
          retention-days: 7

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    needs: get-version
    environment: apple-signing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: npm version ${{ needs.get-version.outputs.version }} --no-git-tag-version

      - name: Build app
        run: npm run build

      # Import certificates for code signing
      - name: Import signing certificate
        if: env.CSC_LINK != ''
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          # Create temporary keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/signing.keychain-db
          KEYCHAIN_PASSWORD=$(openssl rand -base64 32)

          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Import certificate
          echo "$CSC_LINK" | base64 --decode > $RUNNER_TEMP/certificate.p12
          security import $RUNNER_TEMP/certificate.p12 -P "$CSC_KEY_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security list-keychain -d user -s "$KEYCHAIN_PATH"

          # Allow codesign to access the certificate
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

      - name: Build macOS packages
        run: |
          npx electron-builder --mac \
            --x64 --arm64 \
            -p never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Code signing
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # Notarization
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: |
            dist/*.dmg
            dist/*.zip
          retention-days: 7

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: get-version
    environment: windows-signing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: npm version ${{ needs.get-version.outputs.version }} --no-git-tag-version

      - name: Build app
        run: npm run build

      # Import Windows code signing certificate
      - name: Import signing certificate
        if: env.WINDOWS_CSC_LINK != ''
        env:
          WINDOWS_CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK }}
        run: |
          $certBytes = [Convert]::FromBase64String($env:WINDOWS_CSC_LINK)
          [IO.File]::WriteAllBytes("$env:RUNNER_TEMP\certificate.pfx", $certBytes)
        shell: pwsh

      - name: Build Windows packages
        run: |
          npx electron-builder --win --x64 -p never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIN_CSC_LINK: ${{ runner.temp }}\certificate.pfx
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_KEY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-packages
          path: |
            dist/*.exe
            dist/*.msi
          retention-days: 7

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [get-version, build-linux, build-macos, build-windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: List packages
        run: find packages -type f | sort

      # Generate checksums
      - name: Generate checksums
        run: |
          cd packages
          find . -type f \( -name "*.dmg" -o -name "*.exe" -o -name "*.msi" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "*.zip" -o -name "*.tar.gz" \) | while read file; do
            shasum -a 256 "$file" >> ../SHA256SUMS.txt
          done
          cd ..
          cat SHA256SUMS.txt

      # Upload to existing release or create new one
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.get-version.outputs.version }}
          draft: ${{ inputs.draft || false }}
          files: |
            packages/**/*.dmg
            packages/**/*.exe
            packages/**/*.msi
            packages/**/*.AppImage
            packages/**/*.deb
            packages/**/*.rpm
            packages/**/*.zip
            packages/**/*.tar.gz
            SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create summary
        run: |
          echo "## ðŸ–¥ï¸ Electron App Release" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ needs.get-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Packages" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Architecture | Format |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| macOS | x64, arm64 | DMG, ZIP |" >> $GITHUB_STEP_SUMMARY
          echo "| Windows | x64 | EXE, MSI |" >> $GITHUB_STEP_SUMMARY
          echo "| Linux | x64, arm64 | AppImage, DEB, RPM |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Checksums (SHA256)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat SHA256SUMS.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

  # Optional: Update auto-update feed
  update-feed:
    name: Update Auto-Update Feed
    runs-on: ubuntu-latest
    needs: [get-version, publish]
    if: false # Enable if using custom update server

    steps:
      - name: Trigger update feed refresh
        run: |
          # Webhook to update server or S3 bucket
          echo "Update feed refresh would happen here"
          # curl -X POST "$UPDATE_SERVER_WEBHOOK"
