# CLI Binary Publishing Workflow
# Build and publish cross-platform CLI binaries to GitHub Releases
#
# Features:
#   - Cross-platform compilation (Linux, macOS, Windows)
#   - Multi-architecture support (amd64, arm64)
#   - SHA256 checksum generation
#   - Optional code signing (macOS, Windows)
#   - Homebrew formula generation
#   - Scoop manifest generation
#
# Supported languages:
#   - Go (default)
#   - Rust (see comments for configuration)
#
# Prerequisites:
#   1. Go or Rust project with main package
#   2. Semantic version tags (v1.0.0)
#
# Optional secrets:
#   APPLE_DEVELOPER_ID - For macOS code signing
#   APPLE_DEVELOPER_ID_PASSWORD - Apple ID app-specific password
#   WINDOWS_SIGN_CERT - Base64-encoded Windows signing certificate
#   WINDOWS_SIGN_CERT_PASSWORD - Certificate password
#   HOMEBREW_TAP_TOKEN - PAT for updating Homebrew tap
#   SCOOP_BUCKET_TOKEN - PAT for updating Scoop bucket
#
# Customization:
#   - Update BINARY_NAME to match your CLI name
#   - Adjust platforms in the matrix
#   - Enable code signing by uncommenting relevant sections

name: Publish CLI Binaries

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string

env:
  BINARY_NAME: mycli
  # For Rust projects, uncomment:
  # CARGO_TERM_COLOR: always

jobs:
  # Build binaries for all platforms
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ''
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            goos: linux
            goarch: arm64
            ext: ''

          # macOS
          - target: x86_64-apple-darwin
            os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ''
          - target: aarch64-apple-darwin
            os: macos-latest
            goos: darwin
            goarch: arm64
            ext: ''

          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            goos: windows
            goarch: amd64
            ext: '.exe'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      # Go build
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build (Go)
        shell: bash
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          LDFLAGS="-s -w -X main.version=${VERSION}"
          go build -ldflags "${LDFLAGS}" -o "${{ env.BINARY_NAME }}${{ matrix.ext }}" .

      # Rust build (uncomment to use instead of Go)
      # - name: Setup Rust
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     targets: ${{ matrix.target }}
      #
      # - name: Install cross-compilation tools
      #   if: matrix.target == 'aarch64-unknown-linux-gnu'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y gcc-aarch64-linux-gnu
      #
      # - name: Build (Rust)
      #   run: cargo build --release --target ${{ matrix.target }}
      #
      # - name: Move binary
      #   shell: bash
      #   run: |
      #     mv target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}${{ matrix.ext }} .

      # Optional: macOS code signing
      # - name: Sign macOS binary
      #   if: matrix.os == 'macos-latest' && env.APPLE_DEVELOPER_ID != ''
      #   env:
      #     APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
      #   run: |
      #     codesign --force --sign "$APPLE_DEVELOPER_ID" "${{ env.BINARY_NAME }}"

      # Optional: Windows code signing
      # - name: Sign Windows binary
      #   if: matrix.os == 'windows-latest' && env.WINDOWS_SIGN_CERT != ''
      #   env:
      #     WINDOWS_SIGN_CERT: ${{ secrets.WINDOWS_SIGN_CERT }}
      #     WINDOWS_SIGN_CERT_PASSWORD: ${{ secrets.WINDOWS_SIGN_CERT_PASSWORD }}
      #   run: |
      #     echo "$env:WINDOWS_SIGN_CERT" | base64 -d > cert.pfx
      #     signtool sign /f cert.pfx /p "$env:WINDOWS_SIGN_CERT_PASSWORD" /tr http://timestamp.digicert.com /td sha256 /fd sha256 "${{ env.BINARY_NAME }}.exe"

      - name: Create archive
        shell: bash
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          ARCHIVE_NAME="${{ env.BINARY_NAME }}-${VERSION}-${{ matrix.goos }}-${{ matrix.goarch }}"

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "${ARCHIVE_NAME}.zip" "${{ env.BINARY_NAME }}${{ matrix.ext }}" README.md LICENSE
            echo "ARCHIVE=${ARCHIVE_NAME}.zip" >> $GITHUB_ENV
          else
            tar -czvf "${ARCHIVE_NAME}.tar.gz" "${{ env.BINARY_NAME }}${{ matrix.ext }}" README.md LICENSE
            echo "ARCHIVE=${ARCHIVE_NAME}.tar.gz" >> $GITHUB_ENV
          fi

      - name: Generate checksum
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            sha256sum "${{ env.ARCHIVE }}" > "${{ env.ARCHIVE }}.sha256"
          else
            shasum -a 256 "${{ env.ARCHIVE }}" > "${{ env.ARCHIVE }}.sha256"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: |
            ${{ env.ARCHIVE }}
            ${{ env.ARCHIVE }}.sha256
          retention-days: 1

  # Upload all binaries to GitHub Release
  release:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: binary-*
          merge-multiple: true

      - name: Generate combined checksums
        run: |
          cd artifacts
          cat *.sha256 > checksums.txt

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          files: |
            artifacts/*.tar.gz
            artifacts/*.zip
            artifacts/*.sha256
            artifacts/checksums.txt

  # Optional: Update Homebrew tap
  # homebrew:
  #   name: Update Homebrew Tap
  #   runs-on: ubuntu-latest
  #   needs: release
  #   if: github.event_name == 'release'
  #   steps:
  #     - name: Get version
  #       id: version
  #       run: echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
  #
  #     - name: Update Homebrew formula
  #       uses: mislav/bump-homebrew-formula-action@v3
  #       with:
  #         formula-name: ${{ env.BINARY_NAME }}
  #         homebrew-tap: your-org/homebrew-tap
  #         download-url: https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/${{ env.BINARY_NAME }}-${{ steps.version.outputs.version }}-darwin-arm64.tar.gz
  #       env:
  #         COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

  # Optional: Update Scoop bucket
  # scoop:
  #   name: Update Scoop Bucket
  #   runs-on: ubuntu-latest
  #   needs: release
  #   if: github.event_name == 'release'
  #   steps:
  #     - name: Get version
  #       id: version
  #       run: echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
  #
  #     - name: Checkout Scoop bucket
  #       uses: actions/checkout@v4
  #       with:
  #         repository: your-org/scoop-bucket
  #         token: ${{ secrets.SCOOP_BUCKET_TOKEN }}
  #
  #     - name: Update manifest
  #       run: |
  #         VERSION="${{ steps.version.outputs.version }}"
  #         VERSION_NO_V="${VERSION#v}"
  #
  #         cat > bucket/${{ env.BINARY_NAME }}.json << EOF
  #         {
  #           "version": "${VERSION_NO_V}",
  #           "architecture": {
  #             "64bit": {
  #               "url": "https://github.com/${{ github.repository }}/releases/download/${VERSION}/${{ env.BINARY_NAME }}-${VERSION}-windows-amd64.zip",
  #               "hash": "$(curl -sL https://github.com/${{ github.repository }}/releases/download/${VERSION}/${{ env.BINARY_NAME }}-${VERSION}-windows-amd64.zip.sha256 | cut -d' ' -f1)"
  #             }
  #           },
  #           "bin": "${{ env.BINARY_NAME }}.exe",
  #           "checkver": "github",
  #           "autoupdate": {
  #             "architecture": {
  #               "64bit": {
  #                 "url": "https://github.com/${{ github.repository }}/releases/download/v\$version/${{ env.BINARY_NAME }}-v\$version-windows-amd64.zip"
  #               }
  #             }
  #           }
  #         }
  #         EOF
  #
  #     - name: Commit and push
  #       run: |
  #         git config user.name "github-actions[bot]"
  #         git config user.email "github-actions[bot]@users.noreply.github.com"
  #         git add bucket/${{ env.BINARY_NAME }}.json
  #         git commit -m "Update ${{ env.BINARY_NAME }} to ${{ steps.version.outputs.version }}"
  #         git push
