# Google Play Store Publishing Workflow
#
# Publishes Android apps to the Google Play Store using Fastlane.
# Supports internal, alpha, beta, and production tracks.
#
# Features:
#   - Fastlane integration for Play Store upload
#   - AAB (Android App Bundle) signing
#   - Support for multiple release tracks
#   - Version code auto-increment (optional)
#   - Release notes from changelog or input
#
# Required secrets:
#   - PLAY_STORE_SERVICE_ACCOUNT_JSON: Google Cloud service account JSON (base64)
#   - ANDROID_KEYSTORE_BASE64: Signing keystore (base64 encoded)
#   - ANDROID_KEYSTORE_PASSWORD: Keystore password
#   - ANDROID_KEY_ALIAS: Key alias in keystore
#   - ANDROID_KEY_PASSWORD: Key password

name: Publish to Play Store

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      track:
        description: 'Release track'
        required: true
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production
        default: 'internal'
      version_name:
        description: 'Version name (e.g., 1.2.3)'
        required: false
        type: string
      version_code:
        description: 'Version code (leave empty for auto-increment)'
        required: false
        type: string
      release_notes:
        description: 'Release notes (leave empty to use CHANGELOG.md)'
        required: false
        type: string

env:
  JAVA_VERSION: '17'
  RUBY_VERSION: '3.2'

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.version.outputs.version_name }}
      version_code: ${{ steps.version.outputs.version_code }}
      track: ${{ steps.track.outputs.track }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine track
        id: track
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            # Use production for releases, unless it's a prerelease
            if [ "${{ github.event.release.prerelease }}" == "true" ]; then
              TRACK="beta"
            else
              TRACK="production"
            fi
          else
            TRACK="${{ inputs.track }}"
          fi
          echo "track=$TRACK" >> $GITHUB_OUTPUT
          echo "ðŸ“¦ Release track: $TRACK"

      - name: Determine version
        id: version
        run: |
          # Version name
          if [ -n "${{ inputs.version_name }}" ]; then
            VERSION_NAME="${{ inputs.version_name }}"
          elif [ "${{ github.event_name }}" == "release" ]; then
            VERSION_NAME="${{ github.event.release.tag_name }}"
            VERSION_NAME="${VERSION_NAME#v}"
          else
            # Extract from build.gradle
            VERSION_NAME=$(grep -oP 'versionName\s+["\x27]\K[^"\x27]+' app/build.gradle || echo "1.0.0")
          fi

          # Version code
          if [ -n "${{ inputs.version_code }}" ]; then
            VERSION_CODE="${{ inputs.version_code }}"
          else
            # Auto-increment based on current code
            CURRENT_CODE=$(grep -oP 'versionCode\s+\K\d+' app/build.gradle || echo "0")
            VERSION_CODE=$((CURRENT_CODE + 1))
          fi

          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "ðŸ“± Version: $VERSION_NAME ($VERSION_CODE)"

  build:
    name: Build AAB
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > app/release.keystore

      - name: Update version
        run: |
          sed -i "s/versionName \"[^\"]*\"/versionName \"${{ needs.prepare.outputs.version_name }}\"/" app/build.gradle
          sed -i "s/versionCode [0-9]*/versionCode ${{ needs.prepare.outputs.version_code }}/" app/build.gradle

      - name: Build release AAB
        run: |
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 7

      # Optional: Also build APK for direct distribution
      - name: Build release APK
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7

  publish:
    name: Publish to Play Store
    runs-on: ubuntu-latest
    needs: [prepare, build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: release-aab
          path: ./aab

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install Fastlane
        run: |
          gem install fastlane

      - name: Decode service account
        run: |
          echo "${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}" | base64 -d > play-store-key.json

      - name: Prepare release notes
        id: release_notes
        run: |
          mkdir -p fastlane/metadata/android/en-US/changelogs

          if [ -n "${{ inputs.release_notes }}" ]; then
            echo "${{ inputs.release_notes }}" > fastlane/metadata/android/en-US/changelogs/${{ needs.prepare.outputs.version_code }}.txt
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "${{ github.event.release.body }}" > fastlane/metadata/android/en-US/changelogs/${{ needs.prepare.outputs.version_code }}.txt
          elif [ -f "CHANGELOG.md" ]; then
            # Extract latest changelog entry
            sed -n '/^## /,/^## /p' CHANGELOG.md | head -n -1 | tail -n +2 > fastlane/metadata/android/en-US/changelogs/${{ needs.prepare.outputs.version_code }}.txt
          else
            echo "Bug fixes and improvements" > fastlane/metadata/android/en-US/changelogs/${{ needs.prepare.outputs.version_code }}.txt
          fi

          echo "ðŸ“ Release notes:"
          cat fastlane/metadata/android/en-US/changelogs/${{ needs.prepare.outputs.version_code }}.txt

      - name: Upload to Play Store
        run: |
          AAB_PATH=$(find ./aab -name "*.aab" | head -n 1)

          fastlane supply \
            --aab "$AAB_PATH" \
            --track "${{ needs.prepare.outputs.track }}" \
            --json_key "play-store-key.json" \
            --package_name "${{ vars.ANDROID_PACKAGE_NAME || 'com.example.app' }}" \
            --version_code "${{ needs.prepare.outputs.version_code }}" \
            --skip_upload_metadata true \
            --skip_upload_images true \
            --skip_upload_screenshots true

      - name: Create summary
        run: |
          echo "## ðŸ“± Play Store Upload Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Version | ${{ needs.prepare.outputs.version_name }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Version Code | ${{ needs.prepare.outputs.version_code }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Track | ${{ needs.prepare.outputs.track }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ”— [View in Play Console](https://play.google.com/console/)" >> $GITHUB_STEP_SUMMARY

  # Optional: Promote to production after beta testing
  # promote:
  #   name: Promote Release
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   if: false # Enable and configure for promotion workflow
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #
  #     - name: Install Fastlane
  #       run: gem install fastlane
  #
  #     - name: Decode service account
  #       run: |
  #         echo "${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}" | base64 -d > play-store-key.json
  #
  #     - name: Promote to production
  #       run: |
  #         fastlane supply \
  #           --track beta \
  #           --track_promote_to production \
  #           --json_key "play-store-key.json" \
  #           --package_name "${{ vars.ANDROID_PACKAGE_NAME }}" \
  #           --rollout 0.1  # 10% rollout
