# RubyGems Package Publishing
# Publishes Ruby gems to RubyGems.org on release.
#
# Prerequisites:
# 1. Create RubyGems.org account
# 2. Generate API key at https://rubygems.org/profile/api_keys
# 3. Add RUBYGEMS_API_KEY secret
#
# Required secrets:
#   RUBYGEMS_API_KEY - RubyGems.org API key with push permissions
#
# Gem configuration:
# - Version from lib/your_gem/version.rb
# - Metadata from your_gem.gemspec
#
# Documentation:
# - https://guides.rubygems.org/publishing/
# - https://docs.github.com/actions/publishing-packages/publishing-ruby-packages

name: Publish to RubyGems

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (without 'v' prefix)"
        required: true
        type: string

permissions:
  contents: read

env:
  RUBY_VERSION: "3.3"
  # Gem name (should match your .gemspec file name)
  GEM_NAME: your_gem

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION"

      - name: Verify gem version
        run: |
          GEM_VERSION=$(ruby -e "require_relative 'lib/${{ env.GEM_NAME }}/version'; puts ${{ env.GEM_NAME }}::VERSION" 2>/dev/null || \
                        grep -oP "VERSION\s*=\s*['\"]?\K[0-9]+\.[0-9]+\.[0-9]+[^'\"]*" lib/${{ env.GEM_NAME }}/version.rb)
          echo "Gem version: $GEM_VERSION"
          echo "Release version: ${{ steps.version.outputs.version }}"

          if [ "$GEM_VERSION" != "${{ steps.version.outputs.version }}" ]; then
            echo "::error::Gem version ($GEM_VERSION) doesn't match release (${{ steps.version.outputs.version }})"
            echo "Please update lib/${{ env.GEM_NAME }}/version.rb before releasing"
            exit 1
          fi

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test
        # Or: bundle exec rspec

      - name: Build gem
        run: gem build ${{ env.GEM_NAME }}.gemspec

      - name: List gem
        run: ls -la *.gem

      - name: Configure RubyGems credentials
        run: |
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF
          chmod 0600 ~/.gem/credentials

      - name: Push to RubyGems
        run: gem push ${{ env.GEM_NAME }}-${{ steps.version.outputs.version }}.gem

      - name: Cleanup credentials
        if: always()
        run: rm -f ~/.gem/credentials

      # Optional: Also publish to GitHub Packages
      # - name: Push to GitHub Packages
      #   run: |
      #     cat << EOF > ~/.gem/credentials
      #     ---
      #     :github: Bearer ${{ secrets.GITHUB_TOKEN }}
      #     EOF
      #     chmod 0600 ~/.gem/credentials
      #
      #     gem push --key github \
      #       --host https://rubygems.pkg.github.com/${{ github.repository_owner }} \
      #       ${{ env.GEM_NAME }}-${{ steps.version.outputs.version }}.gem

      - name: Summary
        run: |
          echo "## RubyGems Publishing Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Gem:** ${{ env.GEM_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **URL:** https://rubygems.org/gems/${{ env.GEM_NAME }}" >> $GITHUB_STEP_SUMMARY

  # Optional: Notify on publish
  # notify:
  #   name: Notify
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   if: success()
  #   steps:
  #     - name: Announce release
  #       run: |
  #         echo "Gem ${{ env.GEM_NAME }} v${{ steps.version.outputs.version }} published!"
