# Publish Docker Image to Google Container Registry / Artifact Registry
# Builds and pushes container images to GCP container registries
#
# Features:
#   - Workload Identity Federation (OIDC, recommended)
#   - Support for both GCR and Artifact Registry
#   - Multi-architecture builds (amd64, arm64)
#   - Build caching with GitHub Actions cache
#
# Required secrets:
#   GCP_WORKLOAD_IDENTITY_PROVIDER - Workload Identity Provider resource name
#   GCP_SERVICE_ACCOUNT - Service account email for authentication
#     (Alternative: GCP_CREDENTIALS - Service account key JSON)
#
# Required variables:
#   GCP_PROJECT_ID - GCP project ID
#   GCP_REGION - GCP region for Artifact Registry (e.g., us-central1)
#
# Setup:
#   1. Enable Container Registry or Artifact Registry API
#   2. Configure Workload Identity Federation:
#      https://cloud.google.com/iam/docs/workload-identity-federation-with-deployment-pipelines
#   3. Add secrets and variables to repository settings

name: Publish to GCR

on:
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'src/**'
      - '.github/workflows/publish-docker-gcr.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION || 'us-central1' }}
  # Choose one:
  # GCR: gcr.io/PROJECT_ID/IMAGE
  # Artifact Registry: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE
  REGISTRY: ${{ vars.GCP_REGION || 'us-central1' }}-docker.pkg.dev
  IMAGE_NAME: ${{ github.event.repository.name }}
  REPOSITORY: docker-images

jobs:
  build-and-push:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      image: ${{ steps.output.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Recommended: Use Workload Identity Federation
      - name: Authenticate to Google Cloud (Workload Identity)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: access_token

      # Alternative: Use service account key
      # - name: Authenticate to Google Cloud (Service Account Key)
      #   id: auth
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      #     token_format: access_token

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # Alternative: Login to Container Registry (gcr.io)
      # - name: Login to Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: gcr.io
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true

      - name: Output image URI
        id: output
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}"
          echo "Image: $IMAGE"
          echo "Digest: ${{ steps.build.outputs.digest }}"
          echo "image=$IMAGE@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

# Workload Identity Federation Setup:
#
# 1. Create Workload Identity Pool:
#    gcloud iam workload-identity-pools create "github" \
#      --project="${PROJECT_ID}" \
#      --location="global" \
#      --display-name="GitHub Actions Pool"
#
# 2. Create Workload Identity Provider:
#    gcloud iam workload-identity-pools providers create-oidc "github" \
#      --project="${PROJECT_ID}" \
#      --location="global" \
#      --workload-identity-pool="github" \
#      --display-name="GitHub Provider" \
#      --attribute-mapping="google.subject=assertion.sub,attribute.actor=assertion.actor,attribute.repository=assertion.repository" \
#      --issuer-uri="https://token.actions.githubusercontent.com"
#
# 3. Create Service Account:
#    gcloud iam service-accounts create github-actions \
#      --project="${PROJECT_ID}" \
#      --display-name="GitHub Actions"
#
# 4. Grant permissions:
#    gcloud artifacts repositories add-iam-policy-binding docker-images \
#      --project="${PROJECT_ID}" \
#      --location="${REGION}" \
#      --member="serviceAccount:github-actions@${PROJECT_ID}.iam.gserviceaccount.com" \
#      --role="roles/artifactregistry.writer"
#
# 5. Allow impersonation:
#    gcloud iam service-accounts add-iam-policy-binding \
#      "github-actions@${PROJECT_ID}.iam.gserviceaccount.com" \
#      --project="${PROJECT_ID}" \
#      --role="roles/iam.workloadIdentityUser" \
#      --member="principalSet://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/github/attribute.repository/OWNER/REPO"
#
# Get provider resource name:
#    gcloud iam workload-identity-pools providers describe github \
#      --project="${PROJECT_ID}" \
#      --location="global" \
#      --workload-identity-pool="github" \
#      --format="value(name)"
