# Release Please Workflow
#
# Automatically creates release PRs from conventional commits.
# When merged, creates GitHub releases with proper versioning.
#
# IMPORTANT: Post-release step ordering matters!
# - Upload critical assets (PDF, EPUB) BEFORE potentially-failing steps
# - Use continue-on-error for non-critical operations like CITATION.cff updates
#   (which may fail due to branch protection)

name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: your-project-name

  # Post-release tasks: upload assets, update metadata
  # IMPORTANT: Order steps so critical uploads happen before potentially-failing operations
  post-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      # === CRITICAL ASSETS FIRST ===
      # Upload these before any step that might fail

      # Example: Upload PDF to release
      # - name: Upload PDF to release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release upload "${{ needs.release-please.outputs.tag_name }}" \
      #       YOUR_FILE.pdf \
      #       --clobber

      # Example: Build and upload EPUB (for book projects)
      # - name: Install Pandoc
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y pandoc
      #
      # - name: Build EPUB
      #   id: epub
      #   run: |
      #     VERSION="${{ needs.release-please.outputs.version }}"
      #     EPUB_NAME="your-book_v${VERSION}.epub"
      #
      #     pandoc source.tex -o "${EPUB_NAME}" \
      #       --toc --toc-depth=2 \
      #       --metadata title="Your Title" \
      #       --metadata author="Your Name" \
      #       ${COVER_IMAGE:+--epub-cover-image=cover.jpg}
      #
      #     echo "epub_name=${EPUB_NAME}" >> $GITHUB_OUTPUT
      #
      # - name: Upload EPUB to release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release upload "${{ needs.release-please.outputs.tag_name }}" \
      #       "${{ steps.epub.outputs.epub_name }}" \
      #       --clobber

      # === NON-CRITICAL OPERATIONS LAST ===
      # These can fail without blocking the release

      # Example: Update CITATION.cff (may fail due to branch protection)
      - name: Update CITATION.cff
        continue-on-error: true
        run: |
          if [ ! -f CITATION.cff ]; then
            echo "No CITATION.cff file, skipping"
            exit 0
          fi

          VERSION="${{ needs.release-please.outputs.version }}"
          TODAY=$(date +%Y-%m-%d)

          # Update version and date-released
          sed -i "s/^version: .*/version: \"${VERSION}\"/" CITATION.cff
          sed -i "s/^date-released: .*/date-released: \"${TODAY}\"/" CITATION.cff

          echo "Updated CITATION.cff to version $VERSION, date $TODAY"

          # Commit and push (may fail due to branch protection)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CITATION.cff
          git diff --staged --quiet || git commit -m "chore: update CITATION.cff to v${VERSION}"
          git push origin main || echo "::warning::Could not push CITATION.cff update - branch protection may require PR"

      - name: Post-release notification
        run: echo "Release ${{ needs.release-please.outputs.tag_name }} created!"
