name: SBOM Generation

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: sbom.spdx.json
          artifact-name: sbom.spdx.json

      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: sbom.cyclonedx.json
          artifact-name: sbom.cyclonedx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            sbom.spdx.json
            sbom.cyclonedx.json
          retention-days: 90

      # Attach SBOM to release
      - name: Upload SBOM to release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
            sbom.spdx.json \
            sbom.cyclonedx.json \
            --clobber

  # Optional: Scan SBOM for vulnerabilities using Grype
  # scan-sbom:
  #   name: Scan SBOM
  #   runs-on: ubuntu-latest
  #   needs: generate-sbom
  #
  #   steps:
  #     - name: Download SBOM artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: sbom
  #
  #     - name: Scan SBOM with Grype
  #       uses: anchore/scan-action@v4
  #       with:
  #         sbom: sbom.spdx.json
  #         fail-build: false
  #         severity-cutoff: high
