# Secrets Rotation Reminder Workflow
# Scheduled reminders for rotating secrets and integration with GitHub secret scanning
#
# Features:
#   - Scheduled rotation reminders (configurable intervals)
#   - GitHub secret scanning alerts monitoring
#   - Audit logging of rotation events
#   - Slack/Discord notifications
#   - Tracks rotation history
#
# Required secrets:
#   SLACK_WEBHOOK_URL - For Slack notifications (optional)
#   DISCORD_WEBHOOK_URL - For Discord notifications (optional)
#
# Setup:
#   1. Configure rotation schedule (default: monthly)
#   2. Customize the secrets list in the rotation-reminder job
#   3. Enable GitHub secret scanning in repository settings
#   4. Add notification webhooks for your team

name: Secrets Rotation

on:
  schedule:
    # Run on the 1st of every month at 9 AM UTC
    - cron: '0 9 1 * *'

  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'reminder'
        type: choice
        options:
          - reminder
          - audit
          - check-alerts

  # Trigger on secret scanning alerts
  secret_scanning_alert:
    types: [created, resolved]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  # Send rotation reminders
  rotation-reminder:
    name: Secrets Rotation Reminder
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'reminder')

    steps:
      - name: Calculate rotation dates
        id: dates
        run: |
          echo "current_date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "next_month=$(date -u -d '+1 month' +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "ninety_days_ago=$(date -u -d '-90 days' +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Generate rotation reminder
        id: reminder
        run: |
          cat << 'EOF' > reminder.md
          # Monthly Secrets Rotation Reminder

          **Date:** ${{ steps.dates.outputs.current_date }}
          **Repository:** ${{ github.repository }}

          ## Secrets to Review

          Please review and rotate the following secrets if they haven't been updated in the last 90 days:

          ### High Priority (Rotate Every 30 Days)
          - [ ] `PRODUCTION_DATABASE_PASSWORD`
          - [ ] `JWT_SECRET`
          - [ ] `API_ENCRYPTION_KEY`

          ### Standard Priority (Rotate Every 90 Days)
          - [ ] `GITHUB_TOKEN` (auto-rotated by GitHub)
          - [ ] `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`
          - [ ] `SLACK_WEBHOOK_URL`
          - [ ] `DISCORD_WEBHOOK_URL`
          - [ ] Third-party API keys

          ### Low Priority (Rotate Every 180 Days)
          - [ ] `SENTRY_DSN`
          - [ ] Analytics tokens
          - [ ] Read-only API keys

          ## Rotation Checklist

          1. Generate new secret value
          2. Update secret in GitHub repository settings
          3. Update any external systems using the secret
          4. Verify deployments work with new secret
          5. Revoke old secret value
          6. Document rotation in security log

          ## Resources

          - [GitHub Encrypted Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)
          - [Secret Scanning Alerts](https://github.com/${{ github.repository }}/security/secret-scanning)
          - [Security Overview](https://github.com/${{ github.repository }}/security)
          EOF

          echo "Generated rotation reminder"

      - name: Notify via Slack
        if: vars.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":key: Monthly Secrets Rotation Reminder",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":key: Secrets Rotation Reminder",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "It's time to review and rotate secrets for *${{ github.repository }}*.\n\nPlease review the following:\n• Production database credentials\n• API keys older than 90 days\n• JWT and encryption secrets"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Due Date:*\n${{ steps.dates.outputs.next_month }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Secrets",
                        "emoji": true
                      },
                      "url": "https://github.com/${{ github.repository }}/settings/secrets/actions"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Security Overview",
                        "emoji": true
                      },
                      "url": "https://github.com/${{ github.repository }}/security"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Create issue for tracking
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reminder = fs.readFileSync('reminder.md', 'utf8');

            // Check if there's already an open rotation issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'secrets-rotation'
            });

            if (issues.data.length > 0) {
              console.log('Rotation issue already exists, adding comment');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[0].number,
                body: `## Monthly Reminder - ${{ steps.dates.outputs.current_date }}\n\nPlease complete the rotation checklist above.`
              });
            } else {
              console.log('Creating new rotation issue');
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[Security] Secrets Rotation - ${{ steps.dates.outputs.current_date }}`,
                body: reminder,
                labels: ['secrets-rotation', 'security']
              });
            }

  # Check for secret scanning alerts
  check-alerts:
    name: Check Secret Scanning Alerts
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'check-alerts'

    steps:
      - name: Get secret scanning alerts
        id: alerts
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const alerts = await github.rest.secretScanning.listAlertsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
              });

              console.log(`Found ${alerts.data.length} open secret scanning alerts`);

              if (alerts.data.length > 0) {
                const alertSummary = alerts.data.map(alert => ({
                  number: alert.number,
                  secret_type: alert.secret_type,
                  created_at: alert.created_at
                }));

                core.setOutput('has_alerts', 'true');
                core.setOutput('alert_count', alerts.data.length);
                core.setOutput('alerts', JSON.stringify(alertSummary));
              } else {
                core.setOutput('has_alerts', 'false');
                core.setOutput('alert_count', 0);
              }
            } catch (error) {
              if (error.status === 404) {
                console.log('Secret scanning may not be enabled for this repository');
                core.setOutput('has_alerts', 'false');
                core.setOutput('alert_count', 0);
              } else {
                throw error;
              }
            }

      - name: Report alerts
        if: steps.alerts.outputs.has_alerts == 'true'
        run: |
          echo "::warning::Found ${{ steps.alerts.outputs.alert_count }} open secret scanning alerts!"
          echo "Please review: https://github.com/${{ github.repository }}/security/secret-scanning"

  # Handle secret scanning alert events
  alert-handler:
    name: Handle Secret Alert
    runs-on: ubuntu-latest
    if: github.event_name == 'secret_scanning_alert'

    steps:
      - name: Alert created notification
        if: github.event.action == 'created'
        run: |
          echo "::error::New secret scanning alert detected!"
          echo "Alert number: ${{ github.event.alert.number }}"
          echo "Secret type: ${{ github.event.alert.secret_type }}"

      - name: Notify Slack of new alert
        if: github.event.action == 'created' && vars.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":rotating_light: Secret Scanning Alert",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rotating_light: Secret Detected in Repository!",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A potential secret has been detected in *${{ github.repository }}*.\n\n*Immediate action required:*\n1. Revoke the exposed secret\n2. Generate a new secret\n3. Update all systems using this secret\n4. Mark the alert as resolved"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Alert",
                        "emoji": true
                      },
                      "style": "danger",
                      "url": "https://github.com/${{ github.repository }}/security/secret-scanning"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  # Generate audit report
  audit:
    name: Secrets Audit Report
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'audit'

    steps:
      - name: Generate audit report
        uses: actions/github-script@v7
        with:
          script: |
            // Get repository secrets (names only, not values)
            const repoSecrets = await github.rest.actions.listRepoSecrets({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Get environment secrets if any
            const environments = await github.rest.repos.getAllEnvironments({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            let report = `# Secrets Audit Report\n\n`;
            report += `**Generated:** ${new Date().toISOString()}\n`;
            report += `**Repository:** ${context.repo.owner}/${context.repo.repo}\n\n`;

            report += `## Repository Secrets (${repoSecrets.data.total_count})\n\n`;
            report += `| Secret Name | Last Updated |\n`;
            report += `|-------------|-------------|\n`;

            for (const secret of repoSecrets.data.secrets) {
              report += `| \`${secret.name}\` | ${secret.updated_at} |\n`;
            }

            report += `\n## Environments (${environments.data.total_count})\n\n`;

            for (const env of environments.data.environments) {
              report += `### ${env.name}\n\n`;
              report += `- Created: ${env.created_at}\n`;
              report += `- Updated: ${env.updated_at}\n`;

              try {
                const envSecrets = await github.rest.actions.listEnvironmentSecrets({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  environment_name: env.name
                });

                if (envSecrets.data.total_count > 0) {
                  report += `\n| Secret Name | Last Updated |\n`;
                  report += `|-------------|-------------|\n`;
                  for (const secret of envSecrets.data.secrets) {
                    report += `| \`${secret.name}\` | ${secret.updated_at} |\n`;
                  }
                }
              } catch (e) {
                report += `- Unable to list environment secrets\n`;
              }

              report += `\n`;
            }

            console.log(report);

            // Create artifact with report
            const fs = require('fs');
            fs.writeFileSync('secrets-audit-report.md', report);

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: secrets-audit-report
          path: secrets-audit-report.md
          retention-days: 90

# Recommended secrets rotation schedule:
#
# | Secret Type              | Rotation Frequency | Priority |
# |--------------------------|-------------------|----------|
# | Database passwords       | 30 days           | High     |
# | API encryption keys      | 30 days           | High     |
# | JWT signing secrets      | 30 days           | High     |
# | OAuth client secrets     | 90 days           | Medium   |
# | Third-party API keys     | 90 days           | Medium   |
# | Webhook secrets          | 90 days           | Medium   |
# | Monitoring tokens        | 180 days          | Low      |
# | Read-only service tokens | 180 days          | Low      |
#
# Tips:
# - Use GitHub's automatic token rotation where available
# - Consider using OIDC for cloud provider authentication
# - Document all rotation procedures
# - Test rotations in staging before production
# - Set up alerts for secrets approaching rotation deadline
