# Snyk Security Scanning Workflow
# Scan for vulnerabilities in dependencies, containers, and IaC
#
# Features:
#   - Dependency vulnerability scanning
#   - Container image scanning
#   - Infrastructure as Code (IaC) scanning
#   - SARIF integration with GitHub Security tab
#   - PR annotations for vulnerabilities
#
# Prerequisites:
#   1. Snyk account (https://snyk.io)
#   2. Project imported in Snyk
#
# Required secrets:
#   SNYK_TOKEN - Snyk API token
#
# Setup:
#   1. Sign up at https://snyk.io
#   2. Get API token: Account Settings > API Token
#   3. Add SNYK_TOKEN to repository secrets
#
# Customization:
#   - Enable/disable scan types by uncommenting jobs
#   - Adjust severity thresholds
#   - Configure exclusions in .snyk file

name: Snyk Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Dependency vulnerability scanning
  snyk-dependencies:
    name: Dependency Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      # Detect project type and install dependencies
      - name: Setup Node.js
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        if: hashFiles('package.json') != ''
        run: npm ci

      - name: Setup Python
        if: hashFiles('requirements.txt', 'pyproject.toml', 'Pipfile') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Run Snyk dependency scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --sarif-file-output=snyk-deps.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-deps.sarif
        continue-on-error: true

      # Monitor project (only on main branch)
      - name: Monitor project with Snyk
        if: github.ref == 'refs/heads/main'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor
        continue-on-error: true

  # Container image scanning
  snyk-container:
    name: Container Scan
    runs-on: ubuntu-latest
    if: hashFiles('Dockerfile') != ''
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app:${{ github.sha }} .

      - name: Run Snyk container scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: app:${{ github.sha }}
          args: --file=Dockerfile --sarif-file-output=snyk-container.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-container.sarif
        continue-on-error: true

  # Infrastructure as Code scanning
  snyk-iac:
    name: IaC Scan
    runs-on: ubuntu-latest
    if: hashFiles('**/*.tf', '**/terraform/**', '**/cloudformation/**', '**/kubernetes/**', '**/helm/**') != ''
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snyk IaC scan
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-iac.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-iac.sarif
        continue-on-error: true

  # Code scanning (Snyk Code)
  snyk-code:
    name: Code Scan (SAST)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snyk Code scan
        uses: snyk/actions/setup@master

      - name: Snyk Code test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --sarif-file-output=snyk-code.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
        continue-on-error: true

  # Summary job
  summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [snyk-dependencies, snyk-code]
    if: always()
    steps:
      - name: Check scan results
        run: |
          echo "## Snyk Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Scan Type | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Dependencies | ${{ needs.snyk-dependencies.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Code (SAST) | ${{ needs.snyk-code.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View detailed results in the [Security tab](../security/code-scanning)." >> $GITHUB_STEP_SUMMARY
