# Storybook Auto-Publish Workflow
#
# Builds and publishes Storybook documentation for component libraries.
# Provides preview links for PRs and publishes to GitHub Pages on merge.
#
# Features:
#   - Build Storybook on PR and push
#   - Deploy to GitHub Pages (default)
#   - PR comment with preview link
#   - Only rebuild on component changes
#   - Optional Chromatic integration for visual testing
#   - Support for S3/CloudFront deployment
#
# Deployment options:
#   - GitHub Pages (free, default)
#   - S3 + CloudFront
#   - Netlify/Vercel

name: Storybook

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'stories/**'
      - '.storybook/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'stories/**'
      - '.storybook/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-build
          path: storybook-static/
          retention-days: 7

  # Deploy to GitHub Pages on main branch
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: storybook-build
          path: storybook-static/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create summary
        run: |
          echo "## 📚 Storybook Deployed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 **URL:** ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY

  # PR Preview with temporary deployment
  pr-preview:
    name: PR Preview
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: storybook-build
          path: storybook-static/

      # Option 1: Use artifact-based preview (no deployment needed)
      - name: Comment PR with build link
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            // Check for existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('📚 Storybook Preview')
            );

            const body = `## 📚 Storybook Preview

            ✅ **Build successful!**

            | Resource | Link |
            |----------|------|
            | 📦 Artifacts | [Download Storybook Build](${runUrl}#artifacts) |
            | 🔄 Workflow Run | [View Details](${runUrl}) |

            <details>
            <summary>How to preview locally</summary>

            1. Download the \`storybook-build\` artifact from the link above
            2. Extract the zip file
            3. Run \`npx serve storybook-static\` in the extracted directory
            4. Open http://localhost:3000 in your browser

            </details>

            ---
            *Updated: ${new Date().toISOString()}*`;

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

      # Option 2: Deploy to Netlify for live preview
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v3
      #   with:
      #     publish-dir: storybook-static
      #     production-deploy: false
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Storybook preview for PR #${{ github.event.pull_request.number }}"
      #     enable-pull-request-comment: true
      #     enable-commit-comment: false
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  # Optional: Deploy to S3 + CloudFront
  deploy-s3:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    if: false # Enable for S3 deployment

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: storybook-build
          path: storybook-static/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync storybook-static/ s3://${{ vars.S3_BUCKET_NAME }}/ \
            --delete \
            --cache-control "public, max-age=31536000, immutable"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

  # Optional: Chromatic visual testing integration
  chromatic:
    name: Chromatic Visual Tests
    runs-on: ubuntu-latest
    if: false # Enable for Chromatic integration

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          exitZeroOnChanges: true
          onlyChanged: true

# Example package.json scripts:
# {
#   "scripts": {
#     "storybook": "storybook dev -p 6006",
#     "build-storybook": "storybook build -o storybook-static"
#   }
# }

# Required for GitHub Pages deployment:
# 1. Go to Settings > Pages
# 2. Source: GitHub Actions
# 3. The workflow will automatically deploy to: https://<user>.github.io/<repo>/

# For custom domain:
# Add a CNAME file to your storybook-static output or configure in Pages settings
