name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Welcome first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome! 👋

            Thank you for opening your first issue in this repository.

            **Before we proceed:**
            - Please check existing issues to avoid duplicates
            - Provide as much detail as possible
            - For questions, consider using GitHub Discussions

            A maintainer will review your issue soon!

          pr-message: |
            Welcome! 👋

            Thank you for your first pull request!

            **Checklist for contributors:**
            - [ ] Commits follow conventional format (`feat:`, `fix:`, etc.)
            - [ ] Tests pass (if applicable)
            - [ ] Documentation updated (if applicable)

            A maintainer will review your PR soon. Thank you for contributing!
