# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Fail if coverage drops by more than 1%
        threshold: 1%
        # Require at least 70% coverage
        target: 70%
    patch:
      default:
        # Require at least 80% coverage on new code
        target: 80%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Ignore certain files from coverage
ignore:
  - "**/*_test.go"
  - "**/test_*.py"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/tests/**"
  - "**/test/**"
  - "**/__tests__/**"
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/.venv/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/target/**"

# Optional: Define coverage flags for different parts of the codebase
# flags:
#   unit:
#     paths:
#       - src/
#     carryforward: true
#   integration:
#     paths:
#       - tests/integration/
#     carryforward: true
